### ISSUE TITLE
lib-ml todo

### ISSUE THREAD

**Issue by diebolo** [remla24-team8/lib-ml#1]
contains pre-processing for data for training and queries

- [x] get pre-processing logic from urlphishing / model-training repo
- [x] use requirements.txt to get dependencies
- [x] version library automatically by using git version tags
- [x] use a workflow to release lib-ml in a package registry

**Comment by tmtenbrink** [comment]
Did the last 3 things.

**Comment by diebolo** [comment]
Added preprocessing, so issue can be closed.
